### ISSUE TITLE
Snap to grid on multiple objects

### ISSUE THREAD

**Issue by ArthurDavis** [freegroup/draw2d#36]
When selecting multiple objects and moving them, these objects no longer snap to grid. Is it possible to extend this policy to a group selection?

**Comment by freegroup** [comment]
is this ticket still relevant?...if yes I can start to implement a policy to support this feature

**Comment by ucandoit1010** [comment]
> 
> 
> is this ticket still relevant?...if yes I can start to implement a policy to support this feature

yes !!

**Comment by MosabAbuzaid** [comment]
Hi @freegroup did you implement the policy?

**Comment by 28raining** [comment]
Hey, I hit this. When user selects multiple instances and drags, then draw2D crashes. I have a snapToGrid policy.

Crash message:
```
RangeError: Maximum call stack size exceeded
    at Class.getStartPosition (draw2d.js:9013:46)
    at prototype.<computed> [as getStartPosition] (eval at ./node_modules/script-loader/addScript.js.module.exports (draw2d.js:3671:9), <anonymous>:79:26)
    at Class.halfRoute (draw2d.js:22872:23)
    at Class.route (draw2d.js:22845:12)
    at prototype.<computed> [as route] (eval at ./node_modules/script-loader/addScript.js.module.exports (draw2d.js:3671:9), <anonymous>:79:26)
    at Class.calculatePath (draw2d.js:43336:17)
    at Class.calculatePath (draw2d.js:8802:10)
    at prototype.<computed> [as calculatePath] (eval at ./node_modules/script-loader/addScript.js.module.exports (draw2d.js:3671:9), <anonymous>:79:26)
    at Class.repaint (draw2d.js:43351:12)
    at prototype.<computed> [as repaint] (eval at ./node_modules/script-loader/addScript.js.module.exports (draw2d.js:3671:9), <anonymous>:79:26)
```
